# Docker-compose example for a Symfony v4 applcation
version: '3'

services:
  php:
    restart: always
    image: unsimplesistemista/docker-php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      # Uncomment this to use your own SSL certificates
      #- /ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      #- /ssl/server.key:/etc/nginx/ssl/server.key:ro
      # Web (documentRoot) directory is /var/www/public inside the container
      - /var/www:/var/www
      # Uncoment this volume for Symfony v3
      # - /var/www/web:/var/www/public
    logging:
      options:
        max-size: "100m"
